name: metrics
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.13
  - bokeh>=3.7.3
  - panel>=1.8.2
  - hvplot
  - jupyter
  - notebook
  - pandas
  - numpy
  - pre-commit
  - fastparquet
  - panel-material-ui>=0.2.0
  - pip
  - pip:
      - PyGithub
