name: metrics
channels:
  - conda-forge
dependencies:
  - python=3.13
  - bokeh>=3.8
  - panel>=1.8.2
  - holoviews>=1.22.0
  - hvplot>=0.12.2
  - jupyter
  - notebook
  - pandas
  - numpy
  - pre-commit
  - fastparquet
  - panel-material-ui>=0.2.0
  - pip
  - pip:
      - PyGithub
